export const SET_MUMBLE_FONT_COLOR = "SET_MUMBLE_FONT_COLOR";
export const SET_MUMBLE_BACKGROUND_COLOR = "SET_MUMBLE_BACKGROUND_COLOR";
export const SET_MUMBLE_BACKGROUND_IMAGE = "SET_MUMBLE_BACKGROUND_IMAGE";
